### PR TITLE
added support for "bg" attribute for nodes and leaves

### PR DESCRIPTION
**Pull request by pschupp**

### CODE REVIEW

**Comment by talgalili** [comment]
Hey,
Thanks for the PR.
Could you please make sure you update the documents, and also show an example of how the new code works?
(it's not clear to me if just adding these arguments would make this now work out of the box - did you check it?!)

**Comment by pschupp** [comment]
Thank you for the package! I updated "Quick_Introduction.Rmd" with the new options. I tested it myself already and it works well. I wasn't sure whether I should add/change one of the example plots under heading "Setting a dendrogram’s nodes/leaves (points)" in "Quick_Introduction.Rmd", as the change is minor. If you think it is appropriate to change an existing plot to show the new functionality, let me know!

**Comment by talgalili** [comment]
FYI - the pch supported is 21-25 (not 19-21), I will fix the text in followup diff, and will add this example:

```
library("dendextend")

set.seed(23235)
ss <- sample(1:150, 25)

# Getting the dend object
dend <- iris[ss, -5] %>%
   dist() %>%
   hclust() %>%
   as.dendrogram()

dend %>%
   set("labels", 1:25) %>%
   set("nodes_pch", 21) %>% # set all nodes to be pch 21
   set("nodes_col", "darkred") %>%
   set("nodes_bg", "gold") %>%
   set("leaves_pch", 1:25) %>% # Change the leaves pch to move from 1 to 25
   set("leaves_col", "darkred") %>%
   set("leaves_bg", "gold") %>%
   plot(main = "pch 21 to 25 supports the\nnodes_bg and leaves_bg parameters")
```

image

**Comment by talgalili** [comment]
@pschupp - FYI - I've updated dendextend in github to 1.16.0 with your PR. And also added your name to the NEWS file and as a contributor to the DESCRIPTION file.
If you have more PR - you are more than welcome to send the my way :)

**Comment by pschupp** [comment]
Thank you very much. And sorry about misremembering the "pch" numbers, you are right of course!

**Comment by talgalili** [comment]
My pleasure.
No worries.
Feel free to send more PR :)

T

**Comment by talgalili** [comment]
Could you please add a screenshot here with a code snippet to just let me
understand what this will look like?

Thanks!

**Comment by pschupp** [comment]
Hi,
Was this posted in error? It seems that your comment (4th on the thread) provides an excellent example of the behavior. Let me know if this is untrue, though I don't think I can improve on your work.

**Pull request merged**
