### PR TITLE
Add possibility to draw several tanglegrams on same page

### PR DESCRIPTION
**Pull request by CathG**
I modified function `tanglegram.dendrogram` (according to [this SO answer](http://stackoverflow.com/a/39849406/4137985) ) to allow the plotting of 2 or more dendrograms per page.

### CODE REVIEW

**Comment by talgalili** [comment]
Dear @CathG - thank you for the commits. Could you please fix the error coming up in the travis-ci check?
https://travis-ci.org/talgalili/dendextend/builds/168317878

**Comment by CathG** [comment]
@talgalili sorry for the error, I'm trying to fix it as soon as possible

**Comment by talgalili** [comment]
Thank you for the pull request - I merged it and added your name as a contributor to the package. With regards, Tal.

**Comment by CathG** [comment]
Thanks ! :-) Best regards. Cath

**Pull request merged**
