### PR TITLE
Added stepBothSides algorithm to untangle methods

### PR DESCRIPTION
**Pull request by alecbuetow**
Described in the paper 'Shuffle & untangle: novel untangle methods for solving the tanglegram layout problem' (Nguyen et al. 2022), the stepBothSides algorithm has yet to be implemented in a publicly available repository to my knowledge. Here, I have added the option to use this untangling algorithm to the dendextend package in R

### CODE REVIEW

**Comment by talgalili** [comment]
Hey :)
Thanks for the addition.
Could you please also add tests to show the code works?

**Comment by alecbuetow** [comment]
Yes of course! I'll get working on that now

**Comment by alecbuetow** [comment]
Test added to test-untangle.R from my academia affiliated account (f006zvn1)! Let me know if there are any other changes to be made, happy to complete them.

**Comment by talgalili** [comment]
Please also update the DESCRIPTION to add yourself as contributor, and add
a comment to the NEWS file.

**Comment by alecbuetow** [comment]
Completed

**Comment by talgalili** [comment]
I started the tests.
It might fail because of previous issues.
If otherwise it works, I'll take a look at the code today/tomorrow.

**Comment by talgalili** [comment]
Hey,
Could you please update the roxygen2 docs?
(Make sure to mention the new option and give reference to the paper and where the pages wheere specific algorithm is presented)

Thanks!

**Comment by alecbuetow** [comment]
Yep! Will get that done this weekend

**Comment by talgalili** [comment]
Great, thanks.
Please make sure to compile the roxygen2 so that the rd files will be
updated

**Comment by alecbuetow** [comment]
Completed, I believe

**Comment by talgalili** [comment]
Thanks. 
Running tests now.

**Comment by talgalili** [comment]
Hi @alecbuetow 
I've reviewed the code and it generally looks good.
I'm going to merge it, but I'll need to clean up all the other errors in the package before I get it to CRAN.
If you want to help with that, please feel free to submit further PR, and I'll gladly review them.

Thanks for your contribution!
T

**Comment by alecbuetow** [comment]
Thanks for the help in implementation! Happy to try to resolve some of the other errors over the next few weeks

**Comment by talgalili** [comment]
Thanks!
No need.
I've resolved it all during the weekend.
If you have spare time, you could help with adding more unit tests.
I'd be happy to review any PR.

**Comment by alecbuetow** [comment]
Sounds good, is there a to-do list or should I just find the functions lacking unit tests?

**Comment by talgalili** [comment]
@alecbuetow 
You can just go over the files here and it shows exact coverage per line:
https://app.codecov.io/github/talgalili/dendextend/tree/master/R
For example, untangle.R file has ~60% coverage
https://app.codecov.io/github/talgalili/dendextend/blob/master/R%2Funtangle.R

**Pull request merged**
