### PR TITLE
Unbranch keep original ordering

### PR DESCRIPTION
**Pull request by samperochkin**
For sub2 = (sub21, ..., sub24)

unbranch(  dend=(sub1, sub2, sub3) , 2 ) = (sub21, ..., sub24, sub1, sub3)

would now be

unbranch(  dend=(sub1, sub2, sub3) , 2 ) = (sub1, sub21, ..., sub24, sub3).

### CODE REVIEW

**Comment by samperochkin** [comment]
When we face the situation
dend = (leaf1, leaf2, subdend, leaf3)
and
unbranch(dend,3) = (leaf1, leaf2, new.leaf1, new.leaf2, leaf3)

midpoint = mean(midpoints) returns NA and plotting the unbranched dend produces something weird. In this case, I simply defined the midpoint as the original. Again, not sure you (@talgalili) want this. Maybe I should have separated this concern from the "mixed branches" issue.

**Comment by talgalili** [comment]
Hi @samperochkin
Sorry for taking this time to respond!
Can you please provide a minimal example showing the impact of your code?
(if this could be added as a test, that would even be better)

This would help me understand your change and approve it.

Thanks!

**Comment by talgalili** [comment]
Hi again @samperochkin , any chance you could add code demonstrating your changes and/or tests?

**Comment by samperochkin** [comment]
Yes of course, I provide that very soon. Can you please explain me what you mean by "if this could be added as a test, that would even be better"?

**Comment by talgalili** [comment]
You'll need to add examples here:
https://github.com/talgalili/dendextend/blob/master/tests/testthat/test-unbranch.R
Read here to learn about testthat: https://testthat.r-lib.org/

**Comment by samperochkin** [comment]
I've done just that. It's a shame I didn't know about testthat, great tool.

The "problem" I encountered is that the new roots (unbranched) always get placed in slot dend[[1]] and dend[[2]] rather "staying where they were". I think this explains what I mean:

`   hc <- hclust(dist(USArrests[10:13,]), "ave")
   dend <- as.dendrogram(hc)
   unbranched_dend <- unbranch(dend,1)
   unbranched_dend_2 <- unbranch(unbranched_dend,3)
   
   get_leaves_attr(dend,"label")
   get_leaves_attr(unbranched_dend_2,"label") # order of leaves is not preserved
`
The new code leaves the order unchanged.

In addition, I realized that when (after unbranch) all root nodes were leaves, then midpoint was NA, which produced some very weird plot(dend). I will file a separate issue for this.

**Comment by talgalili** [comment]
Perfect. Now I understand what you did, thanks :)
Last request before merging, could you please update:

1)
https://github.com/talgalili/dendextend/blob/master/NEWS
(bump the version to 1.11.0, use current date, and explain your recent change. I'd consider this a bug fix)

2)
https://github.com/talgalili/dendextend/blob/master/DESCRIPTION
(add your details at the end as a contributor, and bump the version to 1.11.0 and update the date)

Thanks :)

**Pull request merged**
