### PR TITLE
Added 2 Tests for Untangle.R

### PR DESCRIPTION
**Pull request by alecbuetow**
Added tests for untangle_best_k_to_rotate_by_1side and untangle_best_k_to_rotate_by_2side_backNforth

### CODE REVIEW

**Comment by alecbuetow** [comment]
Would love to contribute more tests, but I figured I would check in on formatting first. 

These functions aren't referenced anywhere and lack documentation, are you interested in having tests for them?
- untangle_evolution
- untangle_intercourse_evolution
- entanglement_return_best_brother
- untangle_intercourse

Also, would there be any way to retrigger the codecov build? The current version is operating on a commit from 9 months ago.

Thanks as ton as always,
Alec

**Comment by talgalili** [comment]
Hey, thanks :)

1. Merged.
2. Any function should have tests.
3. I checked the codecov build, there is some new definition stuff to do there - and I won't get to it in the coming weeks. Sorry :)


Thanks - keep them coming!

**Comment by alecbuetow** [comment]
Amazing, I'll be out of service in the coming weeks so no rush!

**Comment by talgalili** [comment]
@alecbuetow I've fixed the codecov issue, it's now working properly
https://app.codecov.io/github/talgalili/dendextend

Feel free to continue suggesting more unit tests - thanks!

**Pull request merged**
